import * as path from "path";
import * as fs from "fs/promises";
import * as os from "os";
import { describe, expect, it } from "vitest";
import { GENERATED_FILE_MARKER, generateJavaScriptFromZhjs } from "../src/compiler/generate";
import {
  assertCanWriteGeneratedJsFile,
  getGeneratedJsPath,
  isZhjsFile
} from "../src/utils/file";

describe("generateJavaScriptFromZhjs", () => {
  it("adds the generated file marker and transforms ZhCode source", () => {
    const generated = generateJavaScriptFromZhjs("打印(\"通过\");", {
      sourceFileName: "score.zhjs"
    });

    expect(generated).toContain(GENERATED_FILE_MARKER);
    expect(generated).toContain("from score.zhjs");
    expect(generated).toContain("console.log(\"通过\");");
  });

  it("generates standard JavaScript for score.zhjs-like source", () => {
    const generated = generateJavaScriptFromZhjs(
      [
        "函数 判断成绩(分数) {",
        "  如果 (分数 >= 60) {",
        "    返回 \"通过\";",
        "  } 否则 {",
        "    返回 \"不通过\";",
        "  }",
        "}",
        "",
        "打印(判断成绩(80));"
      ].join("\n"),
      { sourceFileName: "score.zhjs" }
    );

    expect(generated).toContain("function 判断成绩(分数) {");
    expect(generated).toContain("if (分数 >= 60) {");
    expect(generated).toContain("return \"通过\";");
    expect(generated).toContain("console.log(判断成绩(80));");
  });
});

describe("file utilities", () => {
  it("recognizes .zhjs files", () => {
    expect(isZhjsFile("score.zhjs")).toBe(true);
    expect(isZhjsFile("score.js")).toBe(false);
  });

  it("maps .zhjs paths to sibling .js paths", () => {
    expect(getGeneratedJsPath(path.join("examples", "score.zhjs"))).toBe(
      path.join("examples", "score.js")
    );
  });

  it("maps Chinese file names", () => {
    expect(getGeneratedJsPath(path.join("examples", "判断成绩.zhjs"))).toBe(
      path.join("examples", "判断成绩.js")
    );
  });

  it("prevents silently overwriting non-generated JavaScript files", async () => {
    const directory = await fs.mkdtemp(path.join(os.tmpdir(), "zh-code-bridge-"));
    const filePath = path.join(directory, "score.js");
    await fs.writeFile(filePath, "console.log('user code');", "utf8");

    await expect(assertCanWriteGeneratedJsFile(filePath)).rejects.toThrow(
      "目标 .js 文件已存在"
    );
  });

  it("allows overwriting files marked as generated by ZhCode Bridge", async () => {
    const directory = await fs.mkdtemp(path.join(os.tmpdir(), "zh-code-bridge-"));
    const filePath = path.join(directory, "score.js");
    await fs.writeFile(filePath, `// ${GENERATED_FILE_MARKER}\nconsole.log('old');`, "utf8");

    await expect(assertCanWriteGeneratedJsFile(filePath)).resolves.toBeUndefined();
  });
});
