import { transformZhjsToJs } from "./transform";

export const GENERATED_FILE_MARKER = "Generated by ZhCode Bridge";

export interface GenerateJavaScriptOptions {
  sourceFileName?: string;
}

export function generateJavaScriptFromZhjs(
  source: string,
  options: GenerateJavaScriptOptions = {}
): string {
  const sourceFileName = options.sourceFileName ?? "source.zhjs";
  const transformed = transformZhjsToJs(source);

  return `${createGeneratedFileHeader(sourceFileName)}\n${transformed}`;
}

export function createGeneratedFileHeader(sourceFileName: string): string {
  return [
    `// ${GENERATED_FILE_MARKER} from ${sourceFileName}.`,
    "// This file is standard JavaScript.",
    `// Edit ${sourceFileName} if you want to continue using Chinese entry words.`,
    "",
    `// 此文件由 ZhCode Bridge 根据 ${sourceFileName} 自动生成。`,
    "// 这是标准 JavaScript 文件。",
    `// 如果你想继续使用中文入口词，请编辑 ${sourceFileName}。`,
    ""
  ].join("\n");
}
